import type { NodeDefinition, PortDef } from './types';

const f = (id: string, label = id): PortDef => ({ id, label, dataType: 'flow' });
const ev = (id: string, label = id): PortDef => ({ id, label, dataType: 'event' });
const co = (id: string, label = id): PortDef => ({ id, label, dataType: 'condition' });
const bd = (id: string, label = id): PortDef => ({ id, label, dataType: 'body' });
const cb = (id: string, label = id): PortDef => ({ id, label, dataType: 'callback' });

export const NODE_REGISTRY: NodeDefinition[] = [
  {
    command: 'def_module',
    label: 'Module',
    description: 'Declares a custom CCS module',
    category: 'module',
    argHints: ['module-id', 'description'],
    inputs: [],
    outputs: [ev('events', 'events')],
    palette: true,
  },
  {
    command: 'on',
    label: 'on event',
    description: 'Register an event listener',
    category: 'event',
    argHints: [],
    inputs: [ev('module', 'module')],
    outputs: [bd('body', 'body')],
    palette: true,
  },
  {
    command: 'condition',
    label: 'condition',
    description: 'A condition node for if / while',
    category: 'condition',
    argHints: [],
    inputs: [],
    outputs: [co('out', 'out')],
    palette: true,
  },
  {
    command: 'if',
    label: 'if',
    description: 'Branch if condition is true',
    category: 'flow',
    argHints: [],
    inputs: [f('in'), co('condition', 'condition')],
    outputs: [bd('then', 'then'), bd('else', 'else')],
    palette: true,
  },
  {
    command: 'if_not',
    label: 'if_not  (!if)',
    description: 'Branch if condition is false',
    category: 'flow',
    argHints: [],
    inputs: [f('in'), co('condition', 'condition')],
    outputs: [bd('then', 'then'), bd('else', 'else')],
    palette: true,
  },
  {
    command: 'while',
    label: 'while',
    description: 'Loop while condition is true',
    category: 'flow',
    argHints: ['N delay (s)'],
    inputs: [f('in'), co('condition', 'condition')],
    outputs: [bd('loop', 'loop'), f('exit', 'exit')],
    palette: true,
  },
  {
    command: 'while_not',
    label: 'while_not  (!while)',
    description: 'Loop while condition is false',
    category: 'flow',
    argHints: ['N delay (s)'],
    inputs: [f('in'), co('condition', 'condition')],
    outputs: [bd('loop', 'loop'), f('exit', 'exit')],
    palette: true,
  },
  {
    command: 'loop',
    label: 'loop',
    description: 'Repeat N times',
    category: 'flow',
    argHints: ['n (count)'],
    inputs: [f('in')],
    outputs: [bd('body'), f('done')],
    palette: true,
  },
  {
    command: 'loop_period',
    label: 'loop_period',
    description: 'Repeat N times with delay',
    category: 'flow',
    argHints: ['n (times)', 'N (period s)'],
    inputs: [f('in')],
    outputs: [bd('body'), f('done')],
    palette: true,
  },
  {
    command: 'execute',
    label: 'execute',
    description: 'Execute a script block',
    category: 'flow',
    argHints: [],
    inputs: [f('in')],
    outputs: [bd('out')],
    palette: true,
  },
  {
    command: 'execute_random',
    label: 'execute_random',
    description: 'Execute one random line from block',
    category: 'flow',
    argHints: [],
    inputs: [f('in')],
    outputs: [bd('out')],
    palette: true,
  },
  {
    command: 'execute_period',
    label: 'execute_period',
    description: 'Execute block with delay per line',
    category: 'flow',
    argHints: ['N (seconds)'],
    inputs: [f('in')],
    outputs: [bd('out')],
    palette: true,
  },
  {
    command: 'wait',
    label: 'wait',
    description: 'Wait N seconds',
    category: 'flow',
    argHints: ['N (seconds)'],
    inputs: [f('in')],
    outputs: [f('out')],
    palette: true,
  },
  {
    command: 'wait_random',
    label: 'wait_random',
    description: 'Wait random duration',
    category: 'flow',
    argHints: ['N (min)', 'N (max)'],
    inputs: [f('in')],
    outputs: [f('out')],
    palette: true,
  },
  {
    command: 'as',
    label: 'as',
    description: 'Set reference entity',
    category: 'flow',
    argHints: ['target', 'ID (optional)'],
    inputs: [f('in')],
    outputs: [f('out')],
    palette: true,
  },
  {
    command: 'function',
    label: 'function',
    description: 'Call a defined function',
    category: 'flow',
    argHints: ['function-name'],
    inputs: [f('in')],
    outputs: [f('out')],
    palette: true,
  },
  {
    command: 'def_func',
    label: 'def func',
    description: 'Define a reusable function',
    category: 'flow',
    argHints: ['function-name'],
    inputs: [],
    outputs: [bd('body')],
    palette: true,
  },
  {
    command: 'send',
    label: 'send',
    description: 'Send message to client',
    category: 'client',
    argHints: ['"message"'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'say',
    label: 'say',
    description: 'Say in server chat',
    category: 'client',
    argHints: ['"message"'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'print',
    label: 'print',
    description: 'Print to console',
    category: 'client',
    argHints: ['"message"'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'throw',
    label: 'throw',
    description: 'Throw a script exception',
    category: 'client',
    argHints: ['"message"'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'notify',
    label: 'notify',
    description: 'On-screen notification',
    category: 'client',
    argHints: ['N (seconds)', '"message"'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'playsound',
    label: 'playsound',
    description: 'Play a sound',
    category: 'client',
    argHints: ['ID', 'N (volume)', 'N (pitch)'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'module_enable',
    label: 'module enable',
    description: 'Enable a module',
    category: 'client',
    argHints: ['module-id'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'module_disable',
    label: 'module disable',
    description: 'Disable a module',
    category: 'client',
    argHints: ['module-id'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'module_create',
    label: 'module create',
    description: 'Create a module',
    category: 'client',
    argHints: ['module-id'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  { command: 'config_save',   label: 'config save',   description: 'Save config',   category: 'client', argHints: [], inputs: [f('in')], outputs: [], palette: true },
  { command: 'config_load',   label: 'config load',   description: 'Load config',   category: 'client', argHints: [], inputs: [f('in')], outputs: [], palette: true },
  { command: 'config_reload', label: 'config reload', description: 'Reload config', category: 'client', argHints: [], inputs: [f('in')], outputs: [], palette: true },
  {
    command: 'exit',
    label: 'exit',
    description: 'Exit the JVM',
    category: 'client',
    argHints: ['n (exit code)'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'input',
    label: 'input',
    description: 'Simulate a player input',
    category: 'macro',
    argHints: ['input_name'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'hold_input',
    label: 'hold_input',
    description: 'Hold player input for N seconds',
    category: 'macro',
    argHints: ['input_name', 'N (s) | cancel'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'switch',
    label: 'switch',
    description: 'Hotkey to hotbar item',
    category: 'macro',
    argHints: ['ID | back'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  { command: 'swap', label: 'swap', description: 'Swap main/offhand', category: 'macro', argHints: [], inputs: [f('in')], outputs: [], palette: true },
  {
    command: 'drop',
    label: 'drop',
    description: 'Drop from main hand',
    category: 'macro',
    argHints: ['N | all'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'damage',
    label: 'damage',
    description: 'Send attack packet',
    category: 'macro',
    argHints: ['target_type', 'ID'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'turn_to',
    label: 'turn_to',
    description: 'Slowly turn to target, then callback',
    category: 'macro',
    argHints: ['target_type', 'ID'],
    inputs: [f('in')],
    outputs: [cb('then', 'then')],
    palette: true,
  },
  {
    command: 'snap_to',
    label: 'snap_to',
    description: 'Snap to target, then callback',
    category: 'macro',
    argHints: ['target_type', 'ID'],
    inputs: [f('in')],
    outputs: [cb('then', 'then')],
    palette: true,
  },
  {
    command: 'teleport',
    label: 'teleport',
    description: 'Teleport packet',
    category: 'macro',
    argHints: ['~N', '~N', '~N'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'velocity',
    label: 'velocity',
    description: 'Velocity packet',
    category: 'macro',
    argHints: ['~N', '~N', '~N'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  { command: 'gui_drop',      label: 'gui_drop',      description: 'Drop item in GUI',       category: 'macro', argHints: ['ID', 'N | all'],  inputs: [f('in')], outputs: [], palette: true },
  { command: 'gui_switch',    label: 'gui_switch',    description: 'Hover item in GUI',       category: 'macro', argHints: ['ID'],              inputs: [f('in')], outputs: [], palette: true },
  { command: 'gui_swap',      label: 'gui_swap',      description: 'Swap item in GUI',        category: 'macro', argHints: ['ID'],              inputs: [f('in')], outputs: [], palette: true },
  { command: 'gui_quickmove', label: 'gui_quickmove', description: 'Quick-move item in GUI',  category: 'macro', argHints: ['ID', 'n (slot)?'], inputs: [f('in')], outputs: [], palette: true },
  {
    command: 'cancel_packet',
    label: 'cancel_packet',
    description: 'Cancel next packet of type',
    category: 'packet',
    argHints: ['c2s | s2c', 'packetName'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
  {
    command: 'uncancel_packet',
    label: 'uncancel_packet',
    description: 'Remove packet from cancel queue',
    category: 'packet',
    argHints: ['c2s | s2c', 'packetName'],
    inputs: [f('in')],
    outputs: [],
    palette: true,
  },
];

const _map = new Map<string, NodeDefinition>(NODE_REGISTRY.map(d => [d.command, d]));

export function getNodeDef(command: string): NodeDefinition {
  return _map.get(command) ?? {
    command,
    label: command,
    description: 'Unrecognized command',
    category: 'unknown',
    argHints: [],
    inputs: [{ id: 'in', label: 'in', dataType: 'flow' }],
    outputs: [],
    palette: false,
  };
}